name: Lint

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.vue'
      - '**.js'
  pull_request:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.vue'
      - '**.js'


jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install eslint and plugins
        run: npm i -O eslint eslint-plugin-vue @typescript-eslint/parser @typescript-eslint/eslint-plugin typescript

      - uses: haya14busa/action-cond@v1
        id: reporter
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: "github-pr-review"
          if_false: "github-check"

      - name: Run ESLint
        uses: reviewdog/action-eslint@v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          github_token: ${{ secrets.github_token }}
          eslint_flags: 'src/**/*.{ts,vue} {bin,config}/**/*.js'
          reporter: ${{ steps.reporter.outputs.value }}
