name: Release

on:
  push:
    paths-ignore: 
      - "**.md"
    branches:
      - main
  pull_request:
    paths-ignore: 
      - "**.md"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
#        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
        

      - name: Try Build
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ github.event_name != 'pull_request' }}
          max_attempts: 2
          args: --config ./config/electron-builder.js
