name: Release

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main


jobs:
  draft_release:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.clean_changelog }}

    steps:
      - uses: actions/checkout@v2

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "false"
          skip-version-file: true
          skip-commit: true

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          draft: true
          tag_name: v${{ steps.package-version.outputs.current-version }}
          release_name: v${{ steps.package-version.outputs.current-version }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

  build:
    needs: [draft_release]

    strategy:
      matrix:
        os: [windows-latest]
#        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm ci
      - run: npm run build
      - run: npm run electron-builder -- --config.releaseInfo.releaseNotes="${{ needs.draft_release.outputs.changelog }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
