name: Release

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main


jobs:
  draft_release:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}

    steps:
      - uses: actions/checkout@v2

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: changelog
        env:
          REPO: ${{ github.repository }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          draft: true
          tag_name: v${{ steps.package-version.outputs.current-version }}
          release_name: v${{ steps.package-version.outputs.current-version }}
          body: ${{ steps.changelog.outputs.changelog }}

  build:
    needs: [draft_release]

    strategy:
      matrix:
        os: [windows-latest]
#        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm ci
      - run: npm run build
      - name: Save changelog to file
        run: echo "${{ steps.changelog.outputs.changelog }}" > ./build/release-notes.md
      - run: npm run electron-builder
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
