name: Release

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main


jobs:
  draft_release:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
      version: ${{ steps.version.outputs.current-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Get version from current date
        id: version
        run: echo "::set-output name=current-version::$(date '+%-y.%-m.%-d')"

      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: changelog
        env:
          REPO: ${{ github.repository }}

      - name: Delete outdated drafts
        uses: hugo19941994/delete-draft-releases@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Draft
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          draft: true
          tag_name: v${{ steps.version.outputs.current-version }}
          release_name: v${{ steps.version.outputs.current-version }}
          body: ${{ steps.changelog.outputs.changelog }}

  build:
    needs: [draft_release]

    strategy:
      matrix:
        os: [windows-latest]
#        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm ci
      - run: npm run build
      - name: Save changelog to file
        run: |
          mkdir ./build
          echo "${{ needs.draft_release.outputs.changelog }}" > ./build/release-notes.md
      - run: npm run electron-builder --  "-c.extraMetadata.version=${{ needs.draft_release.outputs.version }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
