name: Release

on:
  push:
    paths-ignore: 
      - "**.md"
    branches:
      - main


jobs:
  draft_release:
    runs-on: ubuntu-latest
    outputs:
      body: ${{ steps.release-drafter.output.body }}
      
    steps:
      - uses: actions/checkout@v1
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      
      - uses: release-drafter/release-drafter@v5
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ${{ steps.package-version.outputs.current-version }}
          tag: v${{ steps.package-version.outputs.current-version }}
          name: v${{ steps.package-version.outputs.current-version }}
   
  build:
    needs: [draft_release]
    
    strategy:
      matrix:
        os: [windows-latest]
#        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      
      - run: npm ci
      - run: npm run build
      - run: npm run electron-builder
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
#   release:
#     needs: [build]
#     if: github.event_name == 'pull_request'
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/download-artifact@v2
#         with:
#           name: build-artifact
#           path: dist/app
          
#       - uses: actions/download-artifact@v2
#         with:
#           name: release-notes
#           path: build

#       - uses: pCYSl5EDgo/cat@master
#         id: release-notes
#         with:
#           path: ./build/release-notes.md

#       - name: Upload binaries to release
#         uses: svenstaro/upload-release-action@v2
#         with:
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
#           file: ./dist/app/*
#           file_glob: true
#           tag: v1.0.1
#           overwrite: true
#           body: ${{ steps.release-notes.outputs.text }}
