name: Release

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main


jobs:
  draft_release:
    runs-on: ubuntu-latest
    outputs:
      body: ${{ steps.release-drafter.output.body }}

    steps:
      - uses: actions/checkout@v2

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "false"
          skip-version-file: true
          skip-commit: true

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: v${{ steps.package-version.outputs.current-version }}
          release_name: ${{ steps.package-version.outputs.current-version }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

  build:
    needs: [draft_release]

    strategy:
      matrix:
        os: [windows-latest]
#        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm ci
      - run: npm run build
      - run: npm run electron-builder
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


#   release:
#     needs: [build]
#     if: github.event_name == 'pull_request'
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/download-artifact@v2
#         with:
#           name: build-artifact
#           path: dist/app

#       - uses: actions/download-artifact@v2
#         with:
#           name: release-notes
#           path: build

#       - uses: pCYSl5EDgo/cat@master
#         id: release-notes
#         with:
#           path: ./build/release-notes.md

#       - name: Upload binaries to release
#         uses: svenstaro/upload-release-action@v2
#         with:
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
#           file: ./dist/app/*
#           file_glob: true
#           tag: v1.0.1
#           overwrite: true
#           body: ${{ steps.release-notes.outputs.text }}
