name: Tests
on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'tests/**'
      - 'yarn.lock'
      - '.github/workflows/tests.yml'
  pull_request:
    paths:
      - 'packages/**'
      - 'tests/**'
      - 'yarn.lock'
      - '.github/workflows/tests.yml'

defaults:
  run:
    shell: 'bash'

jobs:
  e2e:
    strategy:
      matrix:
        os: [ windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15 # Need for npm >=7.7

      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v2
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # TODO: Install not all dependencies, but only those required for this workflow
      - name: Install dependencies
        run: npm install -g yarn && yarn install --immutable

      - run: yarn test
